# Generated by Django 6.0 on 2026-03-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('processor_gen', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('for_whom', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Repair', 'In Repair'), ('Damage', 'Damage')], default='Available', max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
        migrations.CreateModel(
            name='ManagementStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('outlook_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Management_staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('major', models.CharField(max_length=10)),
                ('batch_year', models.IntegerField()),
                ('laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.laptop')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
