# Generated by Django 6.0 on 2026-03-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('outlook_mail', models.EmailField(max_length=254)),
                ('person_type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='managementstaff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned')], default='Active', max_length=20),
        ),
        migrations.AlterModelTable(
            name='managementstaff',
            table='management_staff',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('Insert', 'Insert'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=20)),
                ('target_table', models.CharField(max_length=30)),
                ('record_id', models.CharField(max_length=30)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.managementstaff')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='LaptopAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('assignment_status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], max_length=20)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.laptop')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.person')),
            ],
            options={
                'db_table': 'laptop_assignment',
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('report_date', models.DateField()),
                ('replacement_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.laptop')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.laptopassignment')),
            ],
            options={
                'db_table': 'damage_report',
            },
        ),
        migrations.CreateModel(
            name='LaptopReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_date', models.DateField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.laptopassignment')),
                ('new_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_laptop', to='rental_system.laptop')),
                ('old_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_laptop', to='rental_system.laptop')),
            ],
            options={
                'db_table': 'laptop_replacement',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('blacklist_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.person')),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField()),
                ('issue_description', models.TextField()),
                ('repair_cost', models.FloatField()),
                ('repair_shop', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=100)),
                ('repair_status', models.CharField(choices=[('Pending', 'Pending'), ('Repairing', 'Repairing'), ('Completed', 'Completed')], max_length=20)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.laptop')),
            ],
            options={
                'db_table': 'repair_log',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('teacher_status', models.CharField(choices=[('Active', 'Active'), ('Relocated', 'Relocated')], max_length=20)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_system.person')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
