# Generated by Django 6.0 on 2026-03-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0002_person_managementstaff_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
