# Generated by Django 6.0 on 2026-03-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0003_managementstaff_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='for_whom',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], max_length=20),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('Teaching', 'Teaching Staff'), ('Office', 'Office Staff')], max_length=20)),
                ('position', models.CharField(help_text='Rank for Teaching, Role for Office', max_length=50)),
                ('staff_status', models.CharField(choices=[('Active', 'Active'), ('Relocated', 'Relocated'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('FCST', 'FCST'), ('FCS', 'FCS'), ('FIS', 'FIS'), ('ITSM', 'ITSM'), ('FC', 'FC'), ('NS', 'NS'), ('Eng', 'Eng'), ('Myanmar', 'Myanmar')], help_text='Department for Teaching Staff', max_length=100, null=True)),
                ('office_section', models.CharField(blank=True, choices=[('Management', 'Management'), ('Student Affair', 'Student Affair'), ('Library', 'Library'), ('Financial and Accounting', 'Financial and Accounting')], help_text='Section for Office Staff', max_length=100, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_system.person')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
