# Generated by Django 5.2.11 on 2026-03-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0004_alter_laptop_for_whom_alter_person_person_type_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental_system.laptop'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(max_length=100),
        ),
    ]
