# Generated by Django 5.1.7 on 2026-10-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0006_phase_one_security_and_integrity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='laptopassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('actual_return_date__isnull', True), ('assignment_status__in', ['Issued', 'Overdue'])), fields=('person',), name='one_active_assignment_per_person'),
        ),
    ]
